// [key 'New York]: { value: CountyName, label: CountyName, key: CountyName}
// Originally formatted for dropdown components. TODO(Jules): refactor this to returns strings rather than objects?

export interface StateType {
  value: string;
  label: string;
  key: string;
}

export default [
  { value: 'Alabama', label: 'Alabama', key: 'Alabama' },
  { value: 'Alaska', label: 'Alaska', key: 'Alaska' },
  { value: 'Arizona', label: 'Arizona', key: 'Arizona' },
  { value: 'Arkansas', label: 'Arkansas', key: 'Arkansas' },
  { value: 'California', label: 'California', key: 'California' },
  { value: 'Colorado', label: 'Colorado', key: 'Colorado' },
  { value: 'Connecticut', label: 'Connecticut', key: 'Connecticut' },
  { value: 'Delaware', label: 'Delaware', key: 'Delaware' },
  { value: 'Florida', label: 'Florida', key: 'Florida' },
  { value: 'Georgia', label: 'Georgia', key: 'Georgia' },
  { value: 'Hawaii', label: 'Hawaii', key: 'Hawaii' },
  { value: 'Idaho', label: 'Idaho', key: 'Idaho' },
  { value: 'Illinois', label: 'Illinois', key: 'Illinois' },
  { value: 'Indiana', label: 'Indiana', key: 'Indiana' },
  { value: 'Iowa', label: 'Iowa', key: 'Iowa' },
  { value: 'Kansas', label: 'Kansas', key: 'Kansas' },
  { value: 'Kentucky', label: 'Kentucky', key: 'Kentucky' },
  { value: 'Louisiana', label: 'Louisiana', key: 'Louisiana' },
  { value: 'Maine', label: 'Maine', key: 'Maine' },
  { value: 'Maryland', label: 'Maryland', key: 'Maryland' },
  { value: 'Massachusetts', label: 'Massachusetts', key: 'Massachusetts' },
  { value: 'Michigan', label: 'Michigan', key: 'Michigan' },
  { value: 'Minnesota', label: 'Minnesota', key: 'Minnesota' },
  { value: 'Mississippi', label: 'Mississippi', key: 'Mississippi' },
  { value: 'Missouri', label: 'Missouri', key: 'Missouri' },
  { value: 'Montana', label: 'Montana', key: 'Montana' },
  { value: 'Nebraska', label: 'Nebraska', key: 'Nebraska' },
  { value: 'Nevada', label: 'Nevada', key: 'Nevada' },
  { value: 'New Hampshire', label: 'New Hampshire', key: 'New Hampshire' },
  { value: 'New Jersey', label: 'New Jersey', key: 'New Jersey' },
  { value: 'New Mexico', label: 'New Mexico', key: 'New Mexico' },
  { value: 'New York', label: 'New York', key: 'New York' },
  { value: 'North Carolina', label: 'North Carolina', key: 'North Carolina' },
  { value: 'North Dakota', label: 'North Dakota', key: 'North Dakota' },
  { value: 'Ohio', label: 'Ohio', key: 'Ohio' },
  { value: 'Oklahoma', label: 'Oklahoma', key: 'Oklahoma' },
  { value: 'Oregon', label: 'Oregon', key: 'Oregon' },
  { value: 'Pennsylvania', label: 'Pennsylvania', key: 'Pennsylvania' },
  { value: 'Rhode Island', label: 'Rhode Island', key: 'Rhode Island' },
  { value: 'South Carolina', label: 'South Carolina', key: 'South Carolina' },
  { value: 'South Dakota', label: 'South Dakota', key: 'South Dakota' },
  { value: 'Tennessee', label: 'Tennessee', key: 'Tennessee' },
  { value: 'Texas', label: 'Texas', key: 'Texas' },
  { value: 'Utah', label: 'Utah', key: 'Utah' },
  { value: 'Vermont', label: 'Vermont', key: 'Vermont' },
  { value: 'Virginia', label: 'Virginia', key: 'Virginia' },
  { value: 'Washington', label: 'Washington', key: 'Washington' },
  { value: 'West Virginia', label: 'West Virginia', key: 'West Virginia' },
  { value: 'Wisconsin', label: 'Wisconsin', key: 'Wisconsin' },
  { value: 'Wyoming', label: 'Wyoming', key: 'Wyoming' },
] as StateType[];
